#pragma once

#include <cstring>

namespace spektrafilm {

struct TooltipEntry {
  const char *name;
  const char *hint;
};

inline constexpr TooltipEntry kTooltipEntries[] = {
  {"colorGroup", "Input conversion, processing mode, and final SDR, HDR, or Resolve Color Management output."},
  {"filteringGroup", "Camera-side UV and IR filtration before film exposure."},
  {"filmGroup", "Negative stock, exposure, development, density response, and bleach bypass."},
  {"printGroup", "Print material, enlarger exposure, filtration, preflash, and printer-light controls."},
  {"enlargerGroup", "Film-plane crop, scale, and pan before exposure."},
  {"couplerGroup", "DIR coupler redevelopment for contrast and interlayer color interaction."},
  {"grainGroup", "Film format, grain model, particle structure, and animation."},
  {"grainSynthesisGroup", "Advanced controls for Boolean grain-field synthesis."},
  {"halationGroup", "Near-emulsion scatter and film-base highlight reflection."},
  {"diffusionGroup", "Camera and print-stage diffusion filters."},
  {"scannerGroup", "Scanner correction, glare, optical blur, and sharpening."},
  {"infoGroup", "Plugin information and copyright."},
  {"manageGroup", "LUT export, settings copy/paste, user defaults, and factory reset."},

  {"process", "Choose full print simulation, scanned-negative output, or scanned-negative processing through the print stage."},
  {"scanNegativeInvert", "For Scan negative only: normalize the film scan against clear/D-max references and invert negative stocks for display-style viewing. Off leaves the negative-light scan."},
  {"rgbToRawMethod", "Spectral upsampling method used before film exposure."},
  {"inputColorSpace", "Color space expected for the source image."},
  {"rcmInputColorSpace", "Timeline color space used for both input decoding and output encoding in RCM."},
  {"sdrOutputColorSpace", "Display-referred SDR color space for Display Out SDR."},
  {"sceneOutputColorSpace", "Legacy hidden scene-output selector retained for old saved settings."},
  {"outputRole", "Final output path after scanning: SDR display, HDR display, or RCM timeline pass-through."},
  {"hdrPreset", "Common HDR delivery defaults. Manual HDR edits switch the preset to Custom."},
  {"hdrTransfer", "Display Out HDR encoding: Rec.2100 ST2084 (PQ) or Rec.2100 HLG."},
  {"hdrReferenceWhiteNits", "HDR luminance assigned to relative scan white before peak compression, in nits."},
  {"hdrPeakNits", "HDR peak luminance used for tone mapping and PQ/HLG scaling, in nits."},
  {"hdrExposureEv", "Post-scan brightness trim for Display Out HDR. +1 doubles mapped luminance."},
  {"hdrToneMapping", "Highlight handling above reference white. Soft Rolloff gives a gentler shoulder; Hard Clip preserves calibrated headroom to peak."},
  {"colorAdaptation", "Experimental visible-locus input compression for Hanatos and analytical perceptual output gamut compression for SDR/HDR display output. Off preserves the legacy SDR color pipeline."},
  {"colorAdaptationInputCompression", "Use the visible-locus-compressed Hanatos response for RGB-to-raw conversion."},
  {"colorAdaptationCurveSmoothing", "Use smooth density-curve interpolation for film and print development."},
  {"colorAdaptationOutputLightnessCompression", "Apply the OKLch output lightness knee before display encoding."},
  {"colorAdaptationOutputChromaCompression", "Apply OKLch output chroma compression against the destination display gamut."},
  {"cameraUvFilterEnabled", "Apply a camera-side UV cut before film exposure."},
  {"cameraUvCutNm", "Center wavelength of the UV cut transition. Lower values preserve more violet light, in nm."},
  {"cameraIrFilterEnabled", "Apply a camera-side IR cut before film exposure."},
  {"cameraIrCutNm", "Center wavelength of the IR cut transition. Higher values preserve more deep-red light, in nm."},
  {"film", "Film profile used for spectral sensitivity, density curves, grain, and halation defaults."},
  {"filmFormat", "Physical gate size used by film-plane effects. Output resolution changes sampling density, not the simulated format."},
  {"filmPushPullMode", "Standard uses the legacy gamma/timing model. Experimental warps development by layer and tone region."},
  {"filmPushPullStops", "Offsets film development: positive push raises effective speed and contrast; negative pull lowers contrast."},
  {"negativeBleachBypassAmount", "Retains negative silver before print exposure or negative scan, adding density and a black-image overlay before spectral reconstruction."},
  {"negativeLeucoCyanCoupling", "Advanced multiplier for negative-only leuco-cyan dye loss during bleach bypass. 1.0 keeps the physically anchored path."},
  {"paper", "Print paper or print film profile used for the enlarger stage."},
  {"filmExposureEv", "Camera exposure before film density formation. +1 doubles exposure; negative values can offset auto exposure."},
  {"autoExposure", "Meters decoded source luminance and applies a matching film exposure correction."},
  {"autoExposureMethod", "Metering method for auto exposure: center-weighted Gaussian or median luminance."},
  {"filmGamma", "Scales the film density-curve slope. 1.0 keeps the stock profile."},
  {"printExposureEv", "Enlarger exposure applied to the print material. +1 doubles exposure."},
  {"printPushPullStops", "Offsets print or paper development after exposure. Positive push increases contrast; negative pull softens it."},
  {"printBleachBypassAmount", "Retains print silver after development, adding density and a black-image overlay before spectral reconstruction."},
  {"printGamma", "Scales the print density-curve slope. 1.0 keeps the paper profile."},
  {"printShadowShape", "Shapes rendered shadows through the print response. Positive values open shadows while preserving paper black and white."},
  {"printHighlightShape", "Shapes rendered highlights through the print response. Negative values make highlights gentler while preserving paper black and white."},
  {"printTiming", "Print exposure model: spectral enlarger filtration or Academy Printing Density printer-light responsivities."},
  {"filterC", "Cyan enlarger filtration. Higher values reduce red exposure on the print."},
  {"filterMShift", "Magenta filtration trim relative to neutral print balance."},
  {"filterYShift", "Yellow filtration trim relative to neutral print balance."},
  {"enlargerScale", "Magnifies the sampled film area. Higher values show a smaller crop and make physical grain resolve larger."},
  {"enlargerOffsetXPercent", "Horizontal pan of the enlarged film-plane crop, as a percent of the visible frame."},
  {"enlargerOffsetYPercent", "Vertical pan of the enlarged film-plane crop, as a percent of the visible frame."},
  {"preflashExposure", "Uniform pre-exposure added to the paper before image exposure to lift toe detail."},
  {"preflashMFilterShift", "Magenta filtration applied only to the preflash exposure."},
  {"preflashYFilterShift", "Yellow filtration applied only to the preflash exposure."},
  {"printerLightsGang", "Link red, green, and blue printer lights so one edit sets all channels to the same value."},
  {"printerLightsGroup", "Link red, green, and blue printer lights so one edit adds the same delta while preserving offsets."},
  {"printerLightR", "Red printer-light trim."},
  {"printerLightG", "Green printer-light trim."},
  {"printerLightB", "Blue printer-light trim."},
  {"printerLightCalibration", "Apply generated neutral APD calibration offsets. Disable to use raw printer-light values."},
  {"dirAmount", "Overall DIR coupler redevelopment strength. 0 bypasses the effect; 1.0 matches the reference strength."},
  {"dirDiffusionUm", "Lateral diffusion distance for DIR inhibition before redevelopment, in micrometers."},
  {"dirDiffusionTailUm", "Long exponential-tail diffusion distance for DIR inhibition, in micrometers."},
  {"dirDiffusionTailWeight", "Blend from Gaussian DIR diffusion toward the long exponential-tail diffusion model."},
  {"dirInhibitionSameLayer", "Scales same-layer inhibition terms, which mainly shape layer contrast."},
  {"dirInhibitionInterlayer", "Scales interlayer inhibition terms, which mainly shape color separation."},
  {"dirGammaSameLayerRgb", "Same-layer DIR gamma for the red, green, and blue donor layers."},
  {"dirGammaRToGb", "Interlayer DIR gamma from the red donor layer into green and blue receivers."},
  {"dirGammaGToRb", "Interlayer DIR gamma from the green donor layer into red and blue receivers."},
  {"dirGammaBToRg", "Interlayer DIR gamma from the blue donor layer into red and green receivers."},
  {"dirCalibrateToStock", "Restores Python-matching DIR coefficients for the current stock and resumes stock-follow calibration."},
  {"grainEnabled", "Enable film grain synthesis."},
  {"grainModel", "Preview is faster. Production uses layered dye-cloud grain. Grain Synthesis rebuilds density from a stochastic Boolean grain field."},
  {"grainAmount", "Scales the final density-space grain contribution."},
  {"grainSaturation", "Reduces colored grain by blending grain variation toward neutral CMY density."},
  {"grainSublayersEnabled", "Split grain into emulsion sublayers for less uniform density structure."},
  {"grainSubLayerCount", "Number of emulsion sublayers used by production grain."},
  {"grainParticleAreaUm2", "Mean silver-halide particle area before scaling, in square micrometers."},
  {"grainParticleScale", "Per-channel particle-size multipliers for red, green, and blue layers."},
  {"grainParticleScaleLayers", "Particle-size multipliers for the three emulsion depth layers."},
  {"grainDensityMin", "Minimum per-channel grain density contribution."},
  {"grainUniformity", "Higher values make grain more even; lower values increase clumping."},
  {"grainFinalBlurUm", "35mm-equivalent final grain blur, format-compensated for the selected film size."},
  {"grainBlurDyeCloudsUm", "Physical dye-cloud blur used by production grain, in micrometers."},
  {"grainMicroStructure", "Fine grain modulation: X controls strength, Y controls structure wavelength in nm."},
  {"grainSeed", "Random seed for repeatable grain patterns."},
  {"grainAnimate", "Change the grain seed over time so grain moves between frames."},
  {"devStreakGroup", "Uneven development (developer streaks): vertical density bands and per-frame exposure/colour flicker."},
  {"devStreakEnabled", "Simulate developer streaking. Applied to the latent image just before development, so grain and DIR follow the streaks."},
  {"devStreakStrength", "Streak strength. 50 % is the calibrated default; the response steepens past about 30 % and 100 % is roughly 2.6x the default. Amplitude also scales with Film Format."},
  {"devStreakSeed", "Random seed for repeatable streak patterns."},
  {"devStreakAnimate", "Let the streak pattern and exposure flicker evolve from frame to frame. Off freezes frame 0's pattern."},
  {"devStreakAmount", "Extra multiplier on the whole effect (1 = calibrated default)."},
  {"devStreakWidth", "Scales the horizontal size of the bands (1 = calibrated default, higher = wider)."},
  {"devStreakLength", "Scales how far bands stay coherent vertically (1 = calibrated default)."},
  {"devStreakFlicker", "Multiplier on the per-frame global exposure/colour flicker component (1 = calibrated default)."},
  {"devStreakColor", "Inter-layer decorrelation: 0 = neutral streaks, 1 = calibrated colour fluctuation."},
  {"devStreakHold", "How long bands persist between frames (1 = calibrated default, higher = slower change)."},
  {"grainSynthesisSize", "Simple Grain Synthesis size multiplier. Higher values make coarser grains."},
  {"grainSynthesisAmount", "Simple Grain Synthesis blend amount. 0 keeps developed density; 1 uses synthesized density; higher values exaggerate the departure."},
  {"grainSynthesisSharpness", "Simple Grain Synthesis sharpness. Higher values narrow the Monte Carlo observation filter."},
  {"grainSynthesisQuality", "Simple Grain Synthesis quality multiplier. Higher values reduce Monte Carlo noise."},
  {"grainSynthesisSamples", "Monte Carlo samples per output pixel for the filtered Boolean grain model."},
  {"grainSynthesisMeanRadiusUm", "Mean physical grain radius in the film plane before channel and layer scaling, in micrometers."},
  {"grainSynthesisRadiusStdDevRatio", "Log-normal radius variation as a fraction of the mean. 0 uses fixed-radius grains."},
  {"grainSynthesisObservationSigmaUm", "Gaussian observation aperture used by the Monte Carlo estimator, in micrometers."},
  {"grainSynthesisCellSizeRatio", "Poisson partition cell size relative to mean grain radius. Smaller cells reduce per-cell grain counts but scan more cells."},
  {"grainSynthesisMaxRadiusQuantile", "Radius quantile used to truncate log-normal grains for finite local lookup."},
  {"grainSynthesisCoverageEpsilon", "Numerical floor for coverage-to-density conversion near complete grain coverage."},
  {"grainSynthesisMaxGrainsPerCell", "Maximum generated grains per local Poisson cell for predictable GPU cost."},
  {"grainSynthesisRadiusScale", "Per-channel radius multipliers for red, green, and blue-sensitive grain layers."},
  {"grainSynthesisLayerScale", "Per-depth-layer radius multipliers used when layered synthesis is enabled."},
  {"grainSynthesisLayered", "Use generated film layer-density curves so each emulsion depth layer synthesizes its own grain field."},
  {"halationEnabled", "Enable film halation and near-emulsion scatter."},
  {"scatterAmount", "Near-emulsion scatter strength before the longer halation bounce."},
  {"scatterScale", "Radius multiplier for near-emulsion scatter."},
  {"halationAmount", "Strength of red-biased film-base back-reflection around highlights."},
  {"halationScale", "Radius multiplier for film-base halation."},
  {"halationStrength", "Per-channel color weighting for halation return light."},
  {"halationBoostEv", "Extra highlight exposure before camera diffusion, scatter, and halation. 0 leaves the image unchanged."},
  {"halationBoostRange", "Controls how quickly halation highlight boost ramps above the protected exposure."},
  {"halationProtectEv", "Stops above midgray protected from halation highlight boost."},
  {"cameraDiffusionEnabled", "Apply diffusion before film exposure, like a lens filter on the camera."},
  {"cameraDiffusionFamily", "Camera diffusion profile family controlling core, halo, and bloom spread."},
  {"cameraDiffusionStrength", "Overall camera diffusion intensity."},
  {"cameraDiffusionSpatialScale", "Overall camera diffusion radius multiplier."},
  {"cameraDiffusionHaloWarmth", "Warm/cool bias for the camera diffusion halo. Positive values are warmer."},
  {"cameraDiffusionCoreIntensity", "Intensity of tight camera diffusion around bright detail."},
  {"cameraDiffusionCoreSize", "Radius multiplier for tight camera diffusion."},
  {"cameraDiffusionHaloIntensity", "Intensity of mid-radius camera diffusion glow."},
  {"cameraDiffusionHaloSize", "Radius multiplier for mid-radius camera diffusion glow."},
  {"cameraDiffusionBloomIntensity", "Intensity of wide camera diffusion bloom."},
  {"cameraDiffusionBloomSize", "Radius multiplier for wide camera diffusion bloom."},
  {"printDiffusionEnabled", "Apply diffusion in the print stage, like diffusion in the enlarger path."},
  {"printDiffusionFamily", "Print diffusion profile family controlling core, halo, and bloom spread."},
  {"printDiffusionStrength", "Overall print diffusion intensity."},
  {"printDiffusionSpatialScale", "Overall print diffusion radius multiplier."},
  {"printDiffusionHaloWarmth", "Warm/cool bias for the print diffusion halo. Positive values are warmer."},
  {"printDiffusionCoreIntensity", "Intensity of tight print diffusion around bright detail."},
  {"printDiffusionCoreSize", "Radius multiplier for tight print diffusion."},
  {"printDiffusionHaloIntensity", "Intensity of mid-radius print diffusion glow."},
  {"printDiffusionHaloSize", "Radius multiplier for mid-radius print diffusion glow."},
  {"printDiffusionBloomIntensity", "Intensity of wide print diffusion bloom."},
  {"printDiffusionBloomSize", "Radius multiplier for wide print diffusion bloom."},
  {"scannerEnabled", "Enable scanner-stage correction and optics after film or print rendering."},
  {"scannerWhiteCorrection", "Normalize scanner output so the chosen white level maps to display white."},
  {"scannerBlackCorrection", "Normalize scanner output so the chosen black level maps to display black."},
  {"scannerWhiteLevel", "Input level treated as scanner white when white correction is enabled."},
  {"scannerBlackLevel", "Input level treated as scanner black when black correction is enabled."},
  {"glarePercent", "Mean print-scan glare added from the scan illuminant into the output image, as a percent."},
  {"glareRoughness", "Spatial variation of print-scan glare before blur."},
  {"glareBlur", "Gaussian blur radius for the print-scan glare field, in pixels."},
  {"scannerMtf50LpMm", "Scanner optical resolving power. 0 bypasses optical blur; higher values preserve finer film detail, in lp/mm at MTF50."},
  {"scannerUnsharpRadiusUm", "Film-plane radius for scanner unsharp masking, in micrometers."},
  {"scannerUnsharpAmount", "Strength of scanner unsharp masking."},
  {"lutSize", "3D LUT cube resolution. 65 is higher quality; 33 exports faster and creates a smaller file."},
  {"lutDestination", "Folder preset for exported .cube LUTs. User writes to the spektrafilm folder in Movies."},
  {"lutIdentifier", "Custom filename segment placed between the date prefix and random export code."},
  {"exportLut", "Exports a Display Out SDR color-only .cube LUT. RCM and Display Out HDR disable this action."},
  {"presetName", "Visible preset name. Saved files append a timestamp so existing presets are not overwritten."},
  {"presetSelection", "Spektra preset file to load from the user Documents spektrafilm presets folder."},
  {"savePreset", "Saves the current settings as a timestamped preset file using the same snapshot data as Copy Params."},
  {"loadPreset", "Loads the selected preset file and applies matching settings to this plugin instance."},
  {"copyParams", "Copies the current settings to the system clipboard without changing startup defaults."},
  {"pasteParams", "Applies copied Spektra settings from the system clipboard to matching controls in this plugin instance."},
  {"saveDefaults", "Stores the current settings as obfuscated defaults for new Spektra instances."},
  {"resetDefaults", "Deletes saved user defaults and resets the current controls to factory values."},
  {"openUserManual", "Opens the bundled spektrafilm user manual PDF."},
};

inline const char *tooltipForParam(const char *name) {
  for (const TooltipEntry &entry : kTooltipEntries) {
    if (std::strcmp(entry.name, name) == 0) {
      return entry.hint;
    }
  }
  return "";
}

} // namespace spektrafilm
